### PR TITLE
Feature/test branch

### PR DESCRIPTION
**Pull request by jceaser**
I just ran `ruby -r rdoc -e 'puts RDoc::Markup::ToMarkdown.new.convert File.read(ARGV[0] || "README.rdoc")' >README.md` to convert to a format that github would read

### CODE REVIEW

**Comment by jceaser** [comment]
using this pull request to test our setup here

**Comment by charleshuang80** [comment]
so this was just a conversion from `rdoc` to `md`?

**Comment by jceaser** [comment]
lets see if we can merge something simple

**Comment by jceaser** [comment]
yes Charles this was just a conversion, I used the command above, Jon was like "really rdoc" and I wanted to prove we had full access.

**Pull request merged**
